use_frameworks!

platform :ios, '9.0'

target 'SOFileManager_Example' do
  pod 'SOFileManager', :path => '../'

  target 'SOFileManager_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
